server:
  port: 7002
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6002/eureka

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=cart_service_db_dev;encrypt=false
    username: cart_service_app_user
    password: S3cureP@ssw0rd!2025
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true    
    
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s             